version: '3.8'
services:
  nodeodm:
    image: kawtech/oneshot:nodeodm_latest
    ports:
      - "3000:3000"
    volumes:
      - /var/www/data:/var/www/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - bridge_network
      - cvat_cvat

  opensplat:
    image: kawtech/oneshot:opensplat_latest
    runtime: nvidia
    volumes:
      - /var/www/data:/var/www/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - bridge_network
      - cvat_cvat

  flaskapp:
    build:
      context: ./flask
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./flask:/app
      - /var/www/data:/var/www/data
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - nodeodm
      - opensplat
    restart: unless-stopped
    networks:
      - bridge_network
      - cvat_cvat

networks:
  cvat_cvat:
    external: true
  bridge_network:
    driver: bridge
